server:
  port: 9002
spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
dubbo:
  registry:
    address: spring-cloud://localhost
  cloud:
    subscribed-services: nacos-payment-producer