server:
  port: 7003
spring:
  application:
    name: seata-account
  datasource:
    url: jdbc:mysql://172.18.0.182:3307/seata-account?allowMultiQueries=true&autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=CTT
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  cloud:
    alibaba:
      seata:
        tx-service-group: seata-server-tx-group
    nacos:
      discovery:
        server-addr: 172.18.0.199:1111
management:
  endpoint:
    web:
      exposure:
        include: "*"
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.whaa.cloudalibaba.bean